import { useEffect, useState } from 'react';
import { Save, Settings2 } from 'lucide-react';
import type { AppSettings, TechnicianConfig } from '../types/models';

export function ConfigPage({ settings, onSave, initialTech }: { settings: AppSettings; onSave: (next: AppSettings) => Promise<void>; initialTech?: string | null }) {
  const [local, setLocal] = useState(settings);
  const [selected, setSelected] = useState<TechnicianConfig>(settings.technicians.find((t) => t.operario === initialTech) ?? settings.technicians[0]);
  useEffect(() => { setLocal(settings); setSelected(settings.technicians.find((t) => t.operario === initialTech) ?? settings.technicians[0]); }, [settings, initialTech]);
  const updateTech = (patch: Partial<TechnicianConfig>) => setSelected((current) => ({ ...current, ...patch }));
  const saveTech = async () => {
    const next = { ...local, technicians: local.technicians.map((t) => t.operario === selected.operario ? selected : t) };
    setLocal(next); await onSave(next);
  };
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">SISTEMA</div><h1>Configuración</h1><p>Los cambios quedan guardados en el navegador y sobreviven a nuevas importaciones.</p></div></div>
    <div className="config-grid"><section className="panel"><div className="panel-head"><div><h2>Técnicos</h2><p>Configura el punto de inicio que se utilizará para analizar rutas.</p></div></div><div className="tech-config-tabs">{local.technicians.map((t) => <button key={t.operario} className={selected.operario === t.operario ? 'selected' : ''} onClick={() => setSelected(t)}>{t.operario}</button>)}</div><div className="form-grid"><label>OPERARIO<input value={selected.operario} disabled/></label><label>PUNTO DE INICIO<input value={selected.puntoInicio} onChange={(e) => updateTech({ puntoInicio: e.target.value })} placeholder="Ej. Sevilla"/></label><label>DIRECCIÓN<input value={selected.direccion} onChange={(e) => updateTech({ direccion: e.target.value })} placeholder="Dirección del inicio"/></label><label>POBLACIÓN<input value={selected.poblacion} onChange={(e) => updateTech({ poblacion: e.target.value })} /></label><label>PROVINCIA<input value={selected.provincia} onChange={(e) => updateTech({ provincia: e.target.value })}/></label><label>LATITUD<input type="number" value={selected.latitud ?? ''} onChange={(e) => updateTech({ latitud: e.target.value === '' ? null : Number(e.target.value) })}/></label><label>LONGITUD<input type="number" value={selected.longitud ?? ''} onChange={(e) => updateTech({ longitud: e.target.value === '' ? null : Number(e.target.value) })}/></label></div><button className="btn primary" onClick={() => void saveTech()}><Save size={16}/> Guardar técnico</button></section>
    <section className="panel"><div className="panel-head"><div><h2>Routing</h2><p>Sin API key embebida. El proveedor solo se usa cuando se activa.</p></div><Settings2 size={18}/></div><div className="form-grid"><label>PROVEEDOR<select value={local.routing.provider} onChange={(e) => setLocal({ ...local, routing: { ...local.routing, provider: e.target.value as AppSettings['routing']['provider'] }})}><option value="osrm">OSRM</option><option value="openrouteservice">OpenRouteService</option><option value="custom">Otro</option></select></label><label className="span-2">URL DEL SERVICIO<input value={local.routing.url} onChange={(e) => setLocal({ ...local, routing: { ...local.routing, url: e.target.value }})}/></label><label className="span-2">API KEY (opcional)<input type="password" value={local.routing.apiKey} onChange={(e) => setLocal({ ...local, routing: { ...local.routing, apiKey: e.target.value }})}/></label><label className="toggle">ACTIVAR ROUTING<input type="checkbox" checked={local.routing.enabled} onChange={(e) => setLocal({ ...local, routing: { ...local.routing, enabled: e.target.checked }})}/></label></div><button className="btn primary" onClick={() => void onSave(local)}><Save size={16}/> Guardar routing</button></section>
    <section className="panel"><div className="panel-head"><div><h2>Geocodificación</h2><p>Direcciones se cachean en IndexedDB. Si falla, queda como no geolocalizada.</p></div></div><div className="form-grid"><label>PROVEEDOR<select value={local.geocoding.provider} onChange={(e) => setLocal({ ...local, geocoding: { ...local.geocoding, provider: e.target.value as AppSettings['geocoding']['provider'] }})}><option value="nominatim">OpenStreetMap / Nominatim</option><option value="custom">Otro</option></select></label><label className="span-2">URL DEL SERVICIO<input value={local.geocoding.url} onChange={(e) => setLocal({ ...local, geocoding: { ...local.geocoding, url: e.target.value }})}/></label><label className="toggle">ACTIVAR GEOCODIFICACIÓN<input type="checkbox" checked={local.geocoding.enabled} onChange={(e) => setLocal({ ...local, geocoding: { ...local.geocoding, enabled: e.target.checked }})}/></label></div><button className="btn primary" onClick={() => void onSave(local)}><Save size={16}/> Guardar geocodificación</button></section></div>
  </div>;
}
