import { AlertTriangle, CheckCircle2, CircleHelp, Route as RouteIcon } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { TechnicianSummary } from '../types/models';
import { PriorityBadge } from '../components/Badge';
import { formatKm, formatMin } from '../utils/formatUtils';

export function RoutesPage({ summaries, initialTech }: { summaries: TechnicianSummary[]; initialTech?: string | null }) {
  const [selected, setSelected] = useState(initialTech && summaries.some((s) => s.operario === initialTech) ? initialTech : (summaries[0]?.operario ?? ''));
  useEffect(() => { if (initialTech && summaries.some((s) => s.operario === initialTech)) setSelected(initialTech); }, [initialTech, summaries]);
  const summary = summaries.find((s) => s.operario === selected);
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">DESPLAZAMIENTOS</div><h1>Rutas</h1><p>Orden actual por DESDE HORA. No se reordenan arbitrariamente las citas temporales.</p></div><select className="tech-select" value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">Selecciona técnico</option>{summaries.map((s) => <option key={s.operario}>{s.operario}</option>)}</select></div>
    {!summary ? <div className="empty-state"><h3>Sin rutas disponibles</h3><p>Carga incidencias y selecciona un técnico con carga.</p></div> : <div className="route-layout"><div className="route-list">{summary.incidents.map((i, idx) => <div className={`route-stop ${i.conflictoHorario ? 'conflict' : ''}`} key={i.id}><div className="route-time">{i.desdeHora || 'SIN HORA'}</div><div className="route-line"><div className="route-node">{idx + 1}</div>{idx < summary.incidents.length - 1 && <div className="route-stem"/>}</div><div className="route-content"><div className="route-stop-head"><strong>{i.descSede || i.referencia}</strong><PriorityBadge priority={i.prioridad}/></div><div className="muted">{i.descCliente}</div><div className="muted">{i.domicilio || 'Dirección no disponible'}</div><div className="route-meta">{i.tiempoDesdeAnterior !== null ? <span><RouteIcon size={14}/>{formatMin(i.tiempoDesdeAnterior)} · {formatKm(i.distanciaDesdeAnterior ?? 0)}</span> : <span><CircleHelp size={14}/> {i.rutaCalculada ? 'Desplazamiento calculado' : 'Ruta no calculada'}</span>}{i.margenHorario !== null && <span className={i.margenHorario < 0 ? 'danger-text' : ''}>{i.margenHorario < 0 ? 'CONFLICTO HORARIO' : `${i.margenHorario} min de margen de desplazamiento`}</span>}</div>{i.conflictoHorario && <div className="route-warning"><AlertTriangle size={15}/> Conflicto horario</div>}</div></div>)}
    </div><div className="route-side"><div className="side-card"><div className="side-kpi"><span>Incidencias</span><strong>{summary.incidentCount}</strong></div><div className="side-kpi"><span>KM estimados</span><strong>{formatKm(summary.distanceKm)}</strong></div><div className="side-kpi"><span>Desplazamiento</span><strong>{formatMin(summary.travelMin)}</strong></div><div className="side-kpi"><span>Conflictos</span><strong className={summary.conflictCount ? 'danger-text' : ''}>{summary.conflictCount}</strong></div><div className="side-kpi"><span>Geolocalizadas</span><strong>{summary.geocodedCount}/{summary.incidentCount}</strong></div></div><div className="side-note"><CheckCircle2 size={16}/><div><strong>Regla aplicada</strong><p>Las citas con hora se ordenan por hora. Las distancias y tiempos solo aparecen cuando routing devuelve datos.</p></div></div></div></div>}
  </div>;
}

